# Generated by Django 2.2.5 on 2019-12-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.SmallIntegerField(choices=[('23', 23), ('8', 8), ('5', 5), ('0', 0)]),
        ),
    ]
