# Generated by Django 2.2.5 on 2019-12-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0002_auto_20191203_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.FloatField(choices=[('23', 0.23), ('8', 0.08), ('5', 0.05), ('0', 0)]),
        ),
    ]
